config/routes.rb
BackApp::Application.routes.draw do
  resources :tags

  get "add_admin/users"

  get "add_admin/posts"

  get "add_admin/add_admin"

  get "add_admin/add_category"

  get "login/show"

  get "login/login"
  get "login/remove"

  get "posts/vote"
  get "comments/vote"
  get "admin/posts"
  get "admin/users"
  get "admin/edit_admin"
  get "admin/admin_home"
  get "admin/user_impersonate"
  get "posts/search"

  resources :comment_votes

  resources :post_votes

  resources :comments

  resources :posts

  resources :categories

  resources :users

  resources :login

  match'/login/login' => 'login#login'
  post "login/login"

  match'/login/show' => 'login#show'
  get "login/show"

  match 'login/remove' => 'login#remove'
  get "login/remove"

  match 'posts/vote'  => 'posts#vote'
  post "posts/vote"

  match 'comments/vote' => 'comments#vote'
  post "comments/vote"

  match 'admin/posts' => 'admin#posts'
  post "admin/posts"

  match 'admin/show_admin_type' => 'admin#show_admin_type'
  get "admin/show_admin_type"

  match 'admin/new' => 'admin#new'
  post "admin/new"

  match 'admin/users' => 'admin#users'
  post "admin/users"

  match 'admin/create' => 'admin#create'
  post "admin/create"

  match 'admin/view_admin' => 'admin#view_admin'
  post "admin/view_admin"

  match 'admin/delete_admin' => 'admin#delete_admin'
  post "admin/delete_admin"
  match 'admin/delete_post' => 'admin#delete_post'
  post "admin/delete_post"

  match 'admin/delete_user' => 'admin#delete_user'
  post "admin/delete_user"

  match 'admin/add_category' => 'admin#add_category'
  post "admin/add_category"

  match 'admin/view_category' => 'admin#view_category'
 get "admin/view_category"

  match 'admin/user_impersonate' => 'admin#user_impersonate'
  get "admin/user_impersonate"

  match 'admin/stop_impersonate' => 'admin#stop_impersonate'
  get "admin/stop_impersonate"

  match 'posts/search' => 'posts#search'
  get "posts/search"

  match 'posts/display_search' => 'posts#display_search'
  get "posts/display_search"

  match 'posts/index' => 'posts#index'
  post "posts/index"

  root :to => 'posts#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
   include Comparable
  belongs_to :category
  belongs_to :user
  attr_accessible :post_content, :post_title  ,:category_id ,:tags
  has_many :comments
  has_many :tags

  validates :post_title , :presence => true
  validates :post_content , :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :password, :username, :usertype
  has_many :posts

  validates :username , :presence =>true
  validates :password , :presence =>true
  validates :name , :presence =>true
  def User.authenticate (username1,password)
      user1 = User.find_by_username(username1)

  if user1
    pwd =  user1.password
    if pwd==password
      #checking the type of user

      return user1
    end
  end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.find(:all , :order => 'created_at desc')

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @flag = 0
    if(Post.find(params[:id]).user_id == session[:user].id)
    @post = Post.find(params[:id])
    params[:Tags] =  Tag.find_all_by_post_id(@post.id)
    else
      @flag = 1
    end
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])
    @post.user_id = session[:user].id
    respond_to do |format|
      if @post.save
        @postvote = PostVote.new()
        @postvote.post_id = @post.id
        @postvote.user_id = session[:user].id
        @tags = params[:Tags]   # string of all the tags
        @tags_post = @tags.split(" ")  # array containing tags
        @tags_post.each do |tag|
          @tag_obj = Tag.new
          @tag_obj.tag_name = tag
          @tag_obj.post_id= @post.id
          @tag_obj.save
        end


        @postvote.save
        format.html { redirect_to @post, notice: "Post was successfully created " }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])
    @tags = params[:Tags]   # string of all the tags
    @tags_post = @tags.split(" ")  # array containing tags
    @tags_post.each do |tag|
      @tag_obj = Tag.new
      @tag_obj.tag_name = tag
      @tag_obj.post_id= @post.id
      @tag_obj.save
      end
    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy


      @post = Post.find(params[:id])
      @t = Tag.find_all_by_post_id(params[:id])
      @t.each do |tag|
        tag.destroy
        tag.save
      end
      @post.destroy





    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  def vote
    p = Post.find(params[:my_id])
    @owner_of_post = p.user_id
    if(@owner_of_post != session[:user].id)
      if PostVote.count_by_sql("select count(*) from post_votes where user_id=#{session[:user].id} and post_id = #{params[:my_id]}") == 0
        @post_vote = PostVote.new
        @post_vote.user_id = session[:user].id
        @post_vote.post_id = params[:my_id]
        @post_vote.save
        redirect_to(:controller => 'posts',:action => 'index')
      else
        redirect_to(:controller => 'posts',:action => 'index')
      end
    else
      redirect_to(:controller => 'posts',:action => 'index')
    end

  end
  def search
    @search = params[:search]
    @filter = params[:theme]
    if (@filter == 'user')
      session[:search] = 'true'
      @posts = Post.find_all_by_user_id(((User.find_by_username(params[:search])).id))
      redirect_to :controller => 'posts' , :action => 'index' , :post => @posts
    end
  end

  def display_search

  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :post_title %><br />
    <%= f.text_field :post_title %>
  </div>
  <div class="field">
    <%= f.label :post_content %><br />
    <%= f.text_area :post_content , :columns => '10', :rows =>'5' %>
  </div>
    <% @taglist = "" %>
    <% (Tag.find_all_by_post_id(@post)).each do |tag| @taglist += tag.tag_name+" "  end %>

 <label>Tags </label><input type="text" name="Tags"  /> <br/>
    <label> existing tags are : </label> <label><%= "#{@taglist}" %></label>
  <div class="field">
    <%= f.label :add_category  %>
    <%= select("post", "category_id", Category.all.collect{ |c| [ c.category_name, c.id] })  %>
  </div>

  <div class="actions">
    <%= f.submit 'SUBMIT' ,:class=> 'btn btn-primary' %>
  </div>
<% end %>

app/views/posts/display_search.html.erb
<% @flag =0 %>
<% if params[:theme] == 'user' %>
    <% if User.find_by_username(params[:search]) %>
    <% @posts= Post.find_all_by_user_id(((User.find_by_username(params[:search])).id) , :order=>'created_at desc') %>
    <%else %>
    <% @flag =1 %>
    <% end %>
<% end %>
<% if params[:theme] == 'category' %>
    <% if Category.find_by_category_name(params[:search]) %>
<% @posts= Post.find_all_by_category_id(((Category.find_by_category_name(params[:search])).id)) %>
    <% else %>
    <% @flag =1 %>
    <% end %>
<% end %>

<% if params[:theme] == 'tags' %>
    <% if Tag.find_by_tag_name(params[:search]) %>
            <% @tags = Tag.find_all_by_tag_name(params[:search]) %>
    <% @post_ids = [] %>
    <% @tags.each do |tag| @post_ids << tag.post_id end %>
    <% @posts = [] %>
    <% @post_ids.each do |post| @posts << Post.find(post) end %>
    <% else %>
    <% @flag = 1%>
    <% end %>
<% end %>
<% if params[:theme] == 'content' %>
<% @allposts = Post.all %>
<% @posts = [] %>
    <% @allposts.each do |post|  %>

        <% if post.post_content =~ / #{params[:search]}/ || post.post_content =~ /#{params[:search]}/ || post.post_content =~ /#{params[:search]} / || post.post_content =~ / #{params[:search]} / || post.post_title =~ / #{params[:search]} / || post.post_title =~ /#{params[:search]} / || post.post_title =~ / #{params[:search]}/ || post.post_title =~ /#{params[:search]}/  %>
            <% @posts << post %>



        <% end %>
        <% end %>
  <% end %>
<% if @flag > 0 || @posts == []  %>
 <label> Sorry no results found !</label>
 <%= link_to 'Click here to search again !' , :controller => 'posts' , :action=>'search' %>
<% else %>
<h3>Listing posts</h3>

<br/><br/>
<table class="table table-hover table-bordered">
  <tr>
    <th>Post_title</th>
    <th>Post_content</th>
    <th>Category</th>
    <th>User</th>
    <th>#Votes</th>
    <th>#Comments</th>
    <th>Show</th>
    <th>Comment</th>
    <th>Edit</th>
    <th>Destroy</th>

  </tr>

  <% @posts.each do |post| %>
      <%@num = post.id  %>
      <% num_votes = PostVote.count_by_sql "select count(*) from post_votes where post_id =#{@num}" %>
      <% num_comments = Comment.count_by_sql "select count(*) from comments where post_id = #{@num}" %>
      <% @post_user = post.user_id %>
      <% @post_owner = '' %>
      <% if @post_user == 9999 %>
          <% @post_owner = 'Anonymous User' %>
      <% else %>
          <% @post_owner = post.user.username %>
      <% end %>
      <% if session[:user] == nil %>
          <tr>
            <td><%= post.post_title %></td>
            <td><%= post.post_content %></td>
            <td><%= post.category.id %></td>
            <td><%= @post_owner %></td>
            <td><%= "#{num_votes-1}" %></td>
            <td><%= num_comments %></td>
            <td><button class="btn"><%= link_to 'Show', post %></button> </td>

            <td><button class="btn"><%= link_to "Comment" , :controller => 'comments' , :action => 'new', :post_id => post.id %></button></td>
            <td></td>
            <td></td>
          </tr>
      <%else%>
          <% if post.user_id == session[:user].id%>

              <tr>
                <td><%= post.post_title %></td>
                <td class='cols'><%= post.post_content %></td>
                <td><%= post.category.id %></td>
                <td><%= @post_owner %></td>
                <td><%= "#{num_votes-1}" %></td>
                <td><%= num_comments %></td>
                <td><button class="btn"><%= link_to 'Show', post %></button></td>

                <td><button class="btn"><%= link_to "Comment" , :controller => 'comments' , :action => 'new', :post_id => post.id %></button></td>
                <td><button class="btn btn-warning "><%= link_to 'Edit', edit_post_path(post) %></button></td>
                <td><button class="btn btn-danger "><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></button></td>

              </tr>


          <%else%>

              <tr>
                <td><%= post.post_title %></td>
                <td><%= post.post_content %></td>
                <td><%= post.category.id %></td>
                <td><%= @post_owner %></td>
                <td><%= link_to "#{num_votes-1}", :controller => 'posts',:action => 'vote', :my_id => post.id %></td>
                <td><%= num_comments %></td>
                <td><button class="btn"><%= link_to 'Show', post %></button></td>

                <td><button class="btn"><%= link_to "Comment" , :controller => 'comments' , :action => 'new' , :post_id => post.id %></button></td>

                <td></td>
                <td></td>
              </tr>


          <%end%>
      <%end%>
  <%end%>
</table>
<% end %>
<br />

app/views/posts/edit.html.erb
<div class="outerbox">

<h3>Editing post</h3>


<%= render 'form' %>

<button class="btn"><%= link_to 'Show', @post %> </button> |
<button class="btn"> <%= link_to 'Back', posts_path %>    </button>
</div>

app/views/posts/index.html.erb
<div class="row">
  <div class="span4"></div>
  <div class="span8">



  <% @posts.each do |post| %>
  <%@num = post.id  %>
<% num_votes = PostVote.count_by_sql "select count(*) from post_votes where post_id =#{@num}" %>
<% num_comments = Comment.count_by_sql "select count(*) from comments where post_id = #{@num}" %>

<% @post_user = post.user_id %>
        <% @post_owner = '' %>
<% if @post_user == 9999 %>
            <% @post_owner = 'Anonymous User' %>
<% else %>
            <% @post_owner = post.user.username %>
<% end %>

<% if session[:user] == nil %>


            <div class="box">

              <div class="header" >
                <div class="title">  <%= post.post_title %>  </div>
                <div class="createdby"> Created by: <%= @post_owner %></div>
                <div class="category"><%= post.category.category_name %></div>
              </div>
              <hr>
              <div class="content" >
                <%= post.post_content %>

              </div>

              <hr>
              <div class="footer">

                 <i class=" icon-thumbs-up"></i>  <%= "#{num_votes-1}" %>

                <button class="btn show "> <%= link_to 'Show', post %> </button>
                <button type="button" class="btn btn-default comment"><%= link_to "#{num_comments} Comment(s)" , :controller => 'comments' , :action => 'new', :post_id => post.id %></button>

            </div>

            </div>



<%else%>
<% if post.user_id == session[:user].id || session[:user_type] == 'super admin' || session[:user_type] == 'admin'%>



                <div class="box">
                  <div class="header" >
                    <div class="title">  <%= post.post_title %>  </div>
                    <div class="createdby"> Created by: <%= @post_owner %></div>


                    <div class="category"> <%= post.category.category_name %></div>
                  </div>
                  <hr>

                  <div class="content">
                    <%= post.post_content %>

                  </div>

                  <hr>
                       <div class="footer">
                    <button class="btn show "> <%= link_to 'Show', post %> </button>
                    <button type="button " class="btn btn-default comment">  <%= link_to "#{num_comments} Comment(s)" , :controller => 'comments' , :action => 'new', :post_id => post.id %></button>

                   <i class=" icon-thumbs-up"></i> <%= "#{num_votes-1}" %>



                    <button class="btn btn-warning edit  " > <%= link_to 'edit', edit_post_path(post) %> </button>
                    <button class="btn  btn-danger destroy " > <%= link_to 'destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %> </button>


                  </div>
                </div>








<%else%>


                <div class="box">
                  <div class="header" >
                    <div class="title">  <%= post.post_title %>  </div>
                    <div class="createdby"> Created by: <%= @post_owner %></div>
                    <div class="category"> <%= post.category.category_name %></div>
                  </div>
                  <hr>

                  <div class="content">
                    <%= post.post_content %>
                    </div>


                  <hr>
                    <div class="footer">
                    <button class="btn show "> <%= link_to 'Show', post %> </button>


                  <i class=" icon-thumbs-up"></i> <%= link_to "#{num_votes-1}", :controller => 'posts',:action => 'vote', :my_id => post.id ,:class=> 'btn left_btn count1'%>
                    <button type="button " class="btn btn-default comment"><%= link_to "#{num_comments} Comment(s)" , :controller => 'comments' , :action => 'new', :post_id => post.id %></button>

                  </div>
                </div>




<%end%>
  <%end%>
      <%end%>


<br />

  </div>
  <div class="span4" >

   <%= link_to 'New Post', new_post_path, :class => 'btn' %>
      </div>

</div>

app/views/posts/new.html.erb
<div class="outerbox">

  <h3>New post</h3>
  <% if session[:user] == nil%>

      <%= "You are not signed in ! Click on login" %>   <%= link_to 'Login', '/login/login' %>

  <% else %>

      <%= render 'form' %>
  <% end %>
  <br/>
  <%= link_to 'BACK', posts_path, :class => 'btn' %>

</div>

app/views/posts/search.html.erb
<%= form_tag :controller => 'posts', :action => 'display_search' do%>


    <div class="outerbox">

    <p id="failure"><%= flash[:failure] %></p>
    <h3> Search </h3>
    <p>
      <label for = "search">Search :</label>
      <%= text_field_tag :search,params[:search] %>  <br/>

    <div class="form_row">
      <label for="theme">Filter :</label>
      <% ['user','category','content','tags'].each do |theme| %>
          <%= radio_button_tag 'theme', theme, @theme == theme %>
          <%= theme.humanize %>
      <% end %>
    </div>


    </p>

    <p>
      <%= submit_tag "Search" , :class=>'btn' %>
    </p>

    <p>
    <button class="btn"><%= link_to 'Sign Up', new_user_path %>  </button>
    </p>

    </div>
<%end %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>
<% if @post.user_id == 9999 %>
    <% @post_owner = 'Anonymous User' %>
<% else %>
    <% @post_owner = @post.user.username %>
<% end %>

<div class="outerbox">
<p>
  <b>Post title:</b>
  <%= @post.post_title %>
</p>

<p>
  <b>Post content:</b>
  <%= @post.post_content %>
</p>

<p>
  <b>Category:</b>
  <%= @post.category.category_name %>
</p>

<p>
  <b>User:</b>
  <%= @post_owner %>
</p>

  <% if session[:user] != nil %>
<% if @post.user_id == session[:user].id %>
<button class="btn"><%= link_to 'Edit', edit_post_path(@post) %>  </button>
      <button class="btn">     <%= link_to 'Back', posts_path %>   </button>
<%else%>
      <button class="btn">   <%= link_to 'Back', posts_path %>  </button>
<% end %>
      <% else %>
      <button class="btn">   <%= link_to 'Back', posts_path %>  </button>
<% end %>


</div>